# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import task_daemon_pb2 as task__daemon__pb2

GRPC_GENERATED_VERSION = "1.71.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in task_daemon_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class TaskDaemonStub(object):
    """TaskDaemon gRPC service"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueueTask = channel.unary_unary(
            "/taskdaemon.TaskDaemon/QueueTask",
            request_serializer=task__daemon__pb2.TaskRequest.SerializeToString,
            response_deserializer=task__daemon__pb2.TaskResponse.FromString,
            _registered_method=True,
        )
        self.GetTask = channel.unary_unary(
            "/taskdaemon.TaskDaemon/GetTask",
            request_serializer=task__daemon__pb2.TaskIdRequest.SerializeToString,
            response_deserializer=task__daemon__pb2.TaskInfo.FromString,
            _registered_method=True,
        )
        self.GetHealth = channel.unary_unary(
            "/taskdaemon.TaskDaemon/GetHealth",
            request_serializer=task__daemon__pb2.Empty.SerializeToString,
            response_deserializer=task__daemon__pb2.HealthStatus.FromString,
            _registered_method=True,
        )
        self.GetMetrics = channel.unary_unary(
            "/taskdaemon.TaskDaemon/GetMetrics",
            request_serializer=task__daemon__pb2.Empty.SerializeToString,
            response_deserializer=task__daemon__pb2.MetricsSummary.FromString,
            _registered_method=True,
        )
        self.ListTasks = channel.unary_unary(
            "/taskdaemon.TaskDaemon/ListTasks",
            request_serializer=task__daemon__pb2.ListTasksRequest.SerializeToString,
            response_deserializer=task__daemon__pb2.TaskList.FromString,
            _registered_method=True,
        )
        self.DeleteTask = channel.unary_unary(
            "/taskdaemon.TaskDaemon/DeleteTask",
            request_serializer=task__daemon__pb2.TaskIdRequest.SerializeToString,
            response_deserializer=task__daemon__pb2.DeleteResponse.FromString,
            _registered_method=True,
        )
        self.RedriveTask = channel.unary_unary(
            "/taskdaemon.TaskDaemon/RedriveTask",
            request_serializer=task__daemon__pb2.TaskIdRequest.SerializeToString,
            response_deserializer=task__daemon__pb2.RedriveResponse.FromString,
            _registered_method=True,
        )


class TaskDaemonServicer(object):
    """TaskDaemon gRPC service"""

    def QueueTask(self, request, context):
        """Queue a new task"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTask(self, request, context):
        """Get task status and result"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetHealth(self, request, context):
        """Get health status"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetMetrics(self, request, context):
        """Get metrics"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListTasks(self, request, context):
        """List recent tasks"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteTask(self, request, context):
        """Delete a task"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RedriveTask(self, request, context):
        """Redrive a failed task"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_TaskDaemonServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "QueueTask": grpc.unary_unary_rpc_method_handler(
            servicer.QueueTask,
            request_deserializer=task__daemon__pb2.TaskRequest.FromString,
            response_serializer=task__daemon__pb2.TaskResponse.SerializeToString,
        ),
        "GetTask": grpc.unary_unary_rpc_method_handler(
            servicer.GetTask,
            request_deserializer=task__daemon__pb2.TaskIdRequest.FromString,
            response_serializer=task__daemon__pb2.TaskInfo.SerializeToString,
        ),
        "GetHealth": grpc.unary_unary_rpc_method_handler(
            servicer.GetHealth,
            request_deserializer=task__daemon__pb2.Empty.FromString,
            response_serializer=task__daemon__pb2.HealthStatus.SerializeToString,
        ),
        "GetMetrics": grpc.unary_unary_rpc_method_handler(
            servicer.GetMetrics,
            request_deserializer=task__daemon__pb2.Empty.FromString,
            response_serializer=task__daemon__pb2.MetricsSummary.SerializeToString,
        ),
        "ListTasks": grpc.unary_unary_rpc_method_handler(
            servicer.ListTasks,
            request_deserializer=task__daemon__pb2.ListTasksRequest.FromString,
            response_serializer=task__daemon__pb2.TaskList.SerializeToString,
        ),
        "DeleteTask": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteTask,
            request_deserializer=task__daemon__pb2.TaskIdRequest.FromString,
            response_serializer=task__daemon__pb2.DeleteResponse.SerializeToString,
        ),
        "RedriveTask": grpc.unary_unary_rpc_method_handler(
            servicer.RedriveTask,
            request_deserializer=task__daemon__pb2.TaskIdRequest.FromString,
            response_serializer=task__daemon__pb2.RedriveResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "taskdaemon.TaskDaemon", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("taskdaemon.TaskDaemon", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class TaskDaemon(object):
    """TaskDaemon gRPC service"""

    @staticmethod
    def QueueTask(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/taskdaemon.TaskDaemon/QueueTask",
            task__daemon__pb2.TaskRequest.SerializeToString,
            task__daemon__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTask(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/taskdaemon.TaskDaemon/GetTask",
            task__daemon__pb2.TaskIdRequest.SerializeToString,
            task__daemon__pb2.TaskInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetHealth(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/taskdaemon.TaskDaemon/GetHealth",
            task__daemon__pb2.Empty.SerializeToString,
            task__daemon__pb2.HealthStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetMetrics(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/taskdaemon.TaskDaemon/GetMetrics",
            task__daemon__pb2.Empty.SerializeToString,
            task__daemon__pb2.MetricsSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListTasks(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/taskdaemon.TaskDaemon/ListTasks",
            task__daemon__pb2.ListTasksRequest.SerializeToString,
            task__daemon__pb2.TaskList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteTask(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/taskdaemon.TaskDaemon/DeleteTask",
            task__daemon__pb2.TaskIdRequest.SerializeToString,
            task__daemon__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RedriveTask(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/taskdaemon.TaskDaemon/RedriveTask",
            task__daemon__pb2.TaskIdRequest.SerializeToString,
            task__daemon__pb2.RedriveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
